config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :pages
      root :to => 'welcomes#home'
      get 'signup', to: 'users#new'

      get 'login', to: 'sessions#new'
     post 'login', to: 'sessions#create'
     delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :user
  validates :title , presence: true, length: {minimum:2 , maximum: 100}
  validates :description, presence: true, length: {minimum: 2}
  validates :user_id, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pages, dependent: :destroy
  before_save {self.email = email.downcase}
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :username, presence: true,uniqueness: {case_sensitive: false},length: {minimum: 3 , maximum: 25}
validates :email, presence: true,uniqueness: {case_sensitive: false},length: { maximum: 105},format: {with: VALID_EMAIL_REGEX}

has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
     end
   end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:edit, :update, :show, :destroy]
   before_action :require_user, except: [:index, :show]
   before_action :require_same_user, only: [:edit, :update, :destroy]


  # GET /pages
  # GET /pages.json
  def index
    @pages =  Page.paginate(page: params[:page], per_page: 5)
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
  @page = Page.new(page_params)
  @page.user = current_user
  if @page.save
    flash[:success] = "You created your today's memory!"
    redirect_to page_path(@page)
  else
    render 'new'
  end
end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
  if @page.update(page_params)
    flash[:success] = "You have updated the current page!!"
    redirect_to page_path(@page)
  else
    render 'edit'
  end
end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    flash[:danger] = "You deleted that memory!!"
    redirect_to user_path(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:title, :description)
    end

        def require_same_user
        if current_user != @page.user and !current_user.admin?
          flash[:danger]= "You can only edit your own account"
          redirect_to root_path
        end
      end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:success] = "successfully logged in"
    redirect_to new_page_path
  else
    flash.now[:danger] = "Something is wrong with your login information"
    render 'new'
  end
end

def destroy
  session[:user_id] = nil
  flash[:success] = "You hav successfully logged out "
  redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy] 

  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @user_pages = @user.pages.paginate(page: params[:page], per_page: 5)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Add stuffs in your personal diary #{@user.username}"
      redirect_to new_page_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      flash[:success] = "Account was updated successfully!!"
      redirect_to new_page_path
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User was deleted successfully!!"
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger]= "You can only edit your own account"
      redirect_to root_path
    end

    def require_admin
      if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
     end
     end


  end




end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def welcome
    redirect_to @user.pages_path if logged_in?
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Personal Diary</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>


  </head>

  <body>
    <%= render 'partials/navbar' %>
    <%= render 'partials/messages' %> 
    <%= yield %>

  </body>
</html>

app/views/pages/_form.html.erb
<%= render "partials/errors" , obj: @page %>

  <%= form_for(@page, :html => {class: "form-horizontal", role:"form"}) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "How was your day?",autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, class: 'form-control',placeholder: "Wats up buddy!" %>
  </div>

  <div class="actions">
    <%= f.submit "Capture the moments!!"  %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<% obj.each do |page| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="article-title">
        <%= link_to page.title, page_path(page) %>
      </div>
      <div class="article-body">
        <%= truncate(page.description, length: 100) %>
        <div class="article-meta-details">
          <small>created by: <%= page.user.username if page.user %>,
            <%= time_ago_in_words(page.created_at) %> ago.</small>
        </div>

     </div>
        
        </div>

  </div>
</div>
</div>
<% end %>

app/views/pages/edit.html.erb
<h1 class="pad users">Edit your captured memory</h1>

<%= render 'form' %>





<%= render 'partials/footer' %>

app/views/pages/index.html.erb
 <% if logged_in? and current_user.admin?  %>
<h1 class="pad users">Loads of memory <3 </h1>


<div align="center">
  <%= will_paginate %>

</div>


 <%= render 'page', obj: @pages %>

 <div align="center">
   <%= will_paginate %>
 </div>



<%= render 'partials/footer' %>

<% else %>

 <%= render 'partials/userindex' %>

<% end %>

app/views/pages/new.html.erb
<h1  class="pad users">Write today's stuffs buddy</h1>
</br>
<%= render 'partials/messages' %>
<%= render 'form', page: @page %>

<%= render 'partials/footer' %>

app/views/pages/show.html.erb
<h1 class="pad users">Have a look! </h1>

<%= render 'partials/messages' %>
</br>

<div class="well col-xs-8 col-xs-offset-2">

  <h4 class="center"><strong>Description</strong></h4>


  <%= simple_format(@page.description) %>
    <div class="article-actions">
      <% if logged_in? && (current_user == @page.user || current_user.admin?) %>

              <%= link_to "Edit", edit_page_path(@page), class: "btn btn-xs btn-primary" %>
               <%= link_to "delete", page_path(@page), :method => :delete, :data => {confirm: "Are you sure?"},class: "btn btn-xs btn-danger" %>


           <% end %>
   </div>

 </br> </br> </br> </br> </br> </br>
</br> </br> </br> </br> </br> </br> 

 <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
 <!-- // -->

 <div class="container">


   <footer> &copy; Copyright 2017, Likhith Acharya. <br/> All rights reserved. </footer>

     <hr />
         <div class="text-center center-block">
             <br />
               <a href="https://www.facebook.com/likhith.acharya"><i class="fa fa-facebook-square fa-3x social"></i></a>
               <a href="https://twitter.com/likhithacharya"><i class="fa fa-twitter-square fa-3x social"></i></a>
               <a href="https://plus.google.com/106892259531428463432"><i class="fa fa-google-plus-square fa-3x social"></i></a>
               <a href="mailto:likhithacharya277@gmail.com"><i class="fa fa-envelope-square fa-3x social"></i></a>

 </div>
</div>

app/views/partials/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
              prohibited this article from being saved :
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>  

app/views/partials/_footer.html.erb

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<!-- // -->

<div class="container">

  <footer> &copy; Copyright 2017, Likhith Acharya. <br/> All rights reserved. </footer>

    <hr />
        <div class="text-center center-block">
            <br />
              <a href="https://www.facebook.com/likhith.acharya"><i class="fa fa-facebook-square fa-3x social"></i></a>
              <a href="https://twitter.com/likhithacharya"><i class="fa fa-twitter-square fa-3x social"></i></a>
              <a href="https://plus.google.com/106892259531428463432"><i class="fa fa-google-plus-square fa-3x social"></i></a>
              <a href="mailto:likhithacharya277@gmail.com"><i class="fa fa-envelope-square fa-3x social"></i></a>

</div>

app/views/partials/_jumbo.html.erb
<%= render 'partials/navbar' %>
<!-- Full Page Image Background Carousel Header -->
<header id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>


    </ol>

    <!-- Wrapper for Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <!-- Set the first background image using inline CSS below. -->
            <div class="fill" style="background-image:url('https://cdn.shutterstock.com/shutterstock/videos/3089866/thumb/1.jpg ');"></div>
            <div class="carousel-caption">
                <h2>You remember how things made you feel on certain days or in certain places, so your memory is more detailed.</h2>
            </div>
        </div>
        <div class="item">
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('http://3.bp.blogspot.com/-8Al6HZQ7SBM/T87sqUUBcZI/AAAAAAAABmY/6eH_PAWgJNc/s1600/Candle_and_Books.jpg One');"></div>
            <div class="carousel-caption">
                <h2>Make a hot drink, snuggle into a comfy chair and take half an hour just for you and your diary. It feels great!</h2>
            </div>
        </div>

        <div class="item">
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('https://jessicadavidsonauthor.files.wordpress.com/2016/11/website-pen-header.jpeg?w=663&h=373  Two');"></div>
            <div class="carousel-caption">
                <h2>Sometimes, we don’t appreciate what we achieve – writing down a challenge you overcame and how you did it makes you realise this!</h2>
            </div>
        </div>

        <div class="item">
            <!-- Set the second background image using inline CSS below. -->
            <div class="fill" style="background-image:url('https://wallpaperscraft.com/image/library_staircase_room_light_wooden_39639_1920x1080.jpg  Three');"></div>
            <div class="carousel-caption">
                <h2>On the other hand, you can understand things you could have done better, if you have to write something down and consider it.</h2>
            </div>
        </div>

    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>

</header>

<!-- Page Content -->

<!-- /.container -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Script to Activate the Carousel -->
<script>
$('.carousel').carousel({
    interval: 5000 //changes the speed
})
</script>





    <hr />
</div>

app/views/partials/_list.html.erb
<div class="container" id="main" role="main">
    <ul class="menu">
        <li><a href="#">Home</a></li>
        <li><a href="#s1">Menu 1</a>
            <ul class="submenu">
                <li><a href="#">Submenu a</a></li>
                <li><a href="#">Submenu b</a></li>
                <li><a href="#">Submenu c</a></li>
                <li><a href="#">Submenu d</a></li>
                <li><a href="#">Submenu e</a></li>
                <li><a href="#">Submenu f</a></li>
                <li><a href="#">Submenu g</a></li>
                <li><a href="#">Submenu h</a></li>
            </ul>
        </li>
        <li class="active"><a href="#s2">Menu 2</a>
            <ul class="submenu">
                <li><a href="#">Submenu a</a></li>
                <li><a href="#">Submenu b</a></li>
                <li><a href="#">Submenu c</a></li>
                <li><a href="#">Submenu d</a></li>
                <li><a href="#">Submenu e</a></li>
                <li><a href="#">Submenu f</a></li>
                <li><a href="#">Submenu g</a></li>
                <li><a href="#">Submenu h</a></li>
            </ul>
        </li>
        <li><a href="#">Menu 3</a>
            <ul class="submenu">
                <li><a href="#">Submenu a</a></li>
                <li><a href="#">Submenu b</a></li>
                <li><a href="#">Submenu c</a></li>
                <li><a href="#">Submenu d</a></li>
                <li><a href="#">Submenu e</a></li>
                <li><a href="#">Submenu f</a></li>
                <li><a href="#">Submenu g</a></li>
                <li><a href="#">Submenu h</a></li>
            </ul>
        </li>
        <li><a href="#">Menu 4</a></li>
        <li><a href="http://www.script-tutorials.com/whirling-dropdown-menu/">Back to tutorial</a></li>
    </ul>
</div>

app/views/partials/_login.html.erb
<div id="form">

<div class="fish" id="fish"></div>
<div class="fish" id="fish2"></div>

<form id="waterform" method="post">

<div class="formgroup" id="name-form">
    <label for="name">Your name*</label>
    <input type="text" id="name" name="name" />
</div>

<div class="formgroup" id="email-form">
    <label for="email">Your e-mail*</label>
    <input type="email" id="email" name="email" />
</div>

<div class="formgroup" id="message-form">
    <label for="message">Your message</label>
    <textarea id="message" name="message"></textarea>
</div>

	<input type="submit" value="Send your message!" />
</form>
</div>

app/views/partials/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name,msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215</a>
          <%= content_tag :div,msg,:id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
  <% end %>
</div>
</div>

app/views/partials/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <%= link_to "My Personal Diary", root_path, class: "navbar-brand",id:"logo" %>

        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
<% if logged_in? && current_user.admin? %>
              <li><%= link_to "Users" , users_path,class: "nav-icon"  %></li>
              <li><%= link_to "Pages" , pages_path,class: "nav-icon"  %></li>
<% end %>
                     <% if logged_in?  %>
                            <li><%= link_to "Home" , root_path, class: "nav-icon" %></li>
                            <li> <%= link_to "List of my pages",  user_path(current_user), class: "nav-icon" %> </li>
                            <li><%= link_to "Write some today's stuffs!" , new_page_path, class: "nav-icon" %></li>
                            <li><%= link_to "Logout" , logout_path, class: "nav-icon",  method: :delete%></li>
                            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-icon" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "nav-icon"  %> </li>

              </ul>
            </li>
                        <% else %>
                            <li><%= link_to "Home" , root_path, class: "nav-icon" %></li>
                            <li><%= link_to "Log in" , login_path, class: "nav-icon" %></li>
                            <li><%= link_to "sign up" , signup_path, class: "nav-icon" %></li>
                     <% end %>


            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/partials/_userindex.html.erb
<%= render 'partials/jumbo' %>

<%= render 'partials/footer' %>

app/views/users/_form.html.erb
<%= render "partials/errors" , obj: @user %>

  <%= form_for(@user, :html => {class: "form-horizontal", role:"form"}) do |f| %>
  <%= render 'partials/messages' %> 
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control', placeholder: "User name",autofocus: true %>
  </div>

 <% if !logged_in? %>
 <div>
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control', placeholder: "email_id",autofocus: true %>
</div>
 <% end %>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password,  class: 'form-control',placeholder: "Password" %>
  </div>

  <div class="actions">
    <%= f.submit(@user.new_record? ? "Create new account": "Update existing account", class:"btn btn-primary btn-lg") %>
  </div>
<% end %>

app/views/users/_user.html.erb
<% obj.each do |page| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">

      <div class="article-body viewtitle">
             <%= page.title %>
      </div>
      <div class="article-body">
      <%= truncate(page.description, length: 100) %>
        <div class="article-meta-details">
          <small>created by: <%= page.user.username if page.user %>,
            <%= time_ago_in_words(page.created_at) %> ago.</small>
        </div>

     </div>
 <% if logged_in? && (current_user == page.user || current_user.admin?) %>
         <div class="article-actions">
           <%= link_to "View", page_path(page), class: "btn btn-xs btn-primary" %>
           <%= link_to "Edit", edit_page_path(page), class: "btn btn-xs btn-primary" %>
            <%= link_to "delete",page_path(page), :method => :delete, :data => {confirm: "Are you sure?"},class: "btn btn-xs btn-danger" %>
        </div>
  <% end %>
  </div>
</div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1 class="pad users">Editing User</h1>

<%= render 'form', user: @user %>


<%= render 'partials/footer' %>  

app/views/users/index.html.erb
 <% if logged_in? and current_user.admin?  %>
<h1 class="pad users">All Users</h1>

</br>
</br>

 <div align=center>
  <div align="center">
    <%= will_paginate %>
  </div>

   <% @users.each do |user| %>
  <ul class="listing">
    <div class="row">
      <div class="well col-md-4 col-md-offset-4">

        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li><small><%= pluralize(user.pages.count,"page") if user.pages %></small></li>
         <% if logged_in? and current_user.admin?  %>
        <li><%= link_to "Delete this user", user_path(user), method: :delete,
                data: { confirm: "Are you sure you eant to delete user and their pages?"} %></li>
             <% end %>
      </div>

    </div>

  </ul>
  <% end %>
  <%= will_paginate %>
</div>

<%= render 'partials/footer' %>

<% else %>

 <%= render 'partials/userindex' %>

<% end %>

app/views/users/new.html.erb
<h1 class="pad users">Welcome! Now signup for an account.</h1>
<%= render 'partials/messages' %> 


<%= render 'form', user: @user %>



<%= render 'partials/footer' %>

app/views/users/show.html.erb
<h1 class="userpage">Welcome  <%= @user.username %> </h1>

<%= render 'partials/messages' %> 
</br>
<div align="center">
   <%= will_paginate @user_pages %>
</div>

<%= render 'user', obj: @user_pages %>

<div align="center">
   <%= will_paginate @user_pages %>
</div>


<%= render 'partials/footer' %>

app/views/welcomes/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/welcomes/home.html.erb
<%= render 'partials/jumbo' %>

<%= render 'partials/footer' %> 